# 版本
apiVersion: v1
# 類型
kind: Pod
# 紀錄物件的相關資訊，e.g. name, namespace, labels, annotations...
metadata:
  name: kuard
# 將會被存放至 etcd，k8s 將會透過此來建立/更新物件
spec:
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1       # 映像檔
    name: kuard                                 # 容器名稱
    ports:
    - containerPort: 8080                       # 容器內使用的 port
      name: http                                # 描述端口名稱
      protocol: TCP                             # 使用連線方式 TCP UDP
    # 檢查容器應用程式有無正常
    livenessProbe:
      httpGet:                                  # 使用 HTTP GET
        path: /healthy                          # 健檢的路由
        port: 8080                              # PORT
      initialDelaySeconds: 5                    # 容器開啟延遲 n 秒後開始
      timeoutSeconds: 1                         # 請求超時為 n 秒
      periodSeconds: 10                         # 每 n 秒進行健檢
      failureThreshold: 3                       # 連續 n 次失敗重啟容器
