# 版本
apiVersion: v1
# 類型
kind: Pod
# 紀錄物件的相關資訊，e.g. name, namespace, labels, annotations...
metadata:
  name: kuard
# 將會被存放至 etcd，k8s 將會透過此來建立/更新物件
spec:
  # 磁碟區(資料卷)，存放資料的位置
  volumes:
    - name: "kuard-data"
      hostPath:
        path: "/var/lib/kuard"
  containers:
  - image: gcr.io/kuar-demo/kuard-amd64:1       # 映像檔
    name: kuard                                 # 容器名稱
    ports:
    - containerPort: 8080                       # 容器內使用的 port
      name: http                                # 描述端口名稱
      protocol: TCP                             # 使用連線方式 TCP UDP
    # 磁碟區容器掛載的資訊
    volumeMounts:
      - mountPath: "/data"                      # 磁碟區位置
        name: "kuard-data"                      # 磁碟區名稱
